### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray

### ISSUE THREAD

**Issue by JuancaValero** [Andrewnetwork/WorkshopScipy#3]
someone can help me here, I can not solve this problem.

'
digitDict = {}
for i in range(0,10):
    digitDict[i] = []
for i in dataWithLabels:
    digitDict[i[0]].append(i[1])
for i in range(0,10):
    digitDict[i] = np.matrix(digitDict[i])
    print("Digit {0} matrix shape: {1}".format(i,digitDict[i].shape))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-05052c24d917> in <module>()
 15 # Assign a list of image vectors to each corresponding digit class index.
 16 for i in dataWithLabels:
---> 17     digitDict[i[0]].append(i[1])
 18 
 19 # Convert the lists into numpy matricies. (could be done above, but I claim ignorace)

TypeError: unhashable type: numpy.ndarray`

**Comment by Andrewnetwork** [comment]
Hello, what version of python are you using?

**Comment by JuancaValero** [comment]
python 3.6

**Comment by JuancaValero** [comment]
I already solve it, thanks for the attention.
